version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sudoku-postgres
    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: sudoku_user
      POSTGRES_PASSWORD: sudoku_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
