version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sudoku
      POSTGRES_PASSWORD: sudoku_dev_password
      POSTGRES_DB: sudoku_db
    ports:
      - "5432:5432"

volumes:
  postgres-data:
